export const CartTypeAction = {
    ADD_ITEM: 'ADD_ITEM',
    TOGGLE_CART: 'TOGGLE_CART',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    INCREASE_ITEM: 'INCREASE_ITEM',
    DECREASE_ITEM: 'DECREASE_ITEM',
    CLEAR_CART: 'CLEAR_CART'
}